### ISSUE TITLE
异常奔溃not attached to Activity

### ISSUE THREAD

**Issue by SwordSware** [bugyun/AvoidOnResultHelper#4]
在实际使用中有时会出现奔溃，报错信息：java.lang.IllegalStateException: Fragment AvoidOnResultFragment{427229a} (01ae2f57-b263-4c79-87cc-e5c405cdb5e9) RYAvoidOnResultHelper} not attached to Activity

at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1420)

at vip.ruoyun.helper.avoid.AvoidOnResultFragment.startActivityForResult(AvoidOnResultFragment.java:60)

at vip.ruoyun.helper.avoid.AvoidOnResultHelper.startActivityForResult(AvoidOnResultHelper.java:63)

at vip.ruoyun.helper.avoid.AvoidOnResultHelper.startActivityForResult(AvoidOnResultHelper.java:58)

估计在activity重建时，AvoidOnResultFragment中的startActivityForResult 因为AvoidOnResultFragment脱离了activity绑定，导致此奔溃，建议用到context相关的地方，需要判断isAdded()

**Comment by bugyun** [comment]
好的，多谢提交问题

**Comment by wzg-githome** [comment]
> 好的，多谢提交问题

java.lang.IllegalStateException: Fragment AvoidOnResultFragment{427229a} (01ae2f57-b263-4c79-87cc-e5c405cdb5e9) RYAvoidOnResultHelper} not attach to Activity--问题解决了吗？
我也发生了这个问题
